package conv1;

import java.text.DecimalFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class conv1_0 extends javax.swing.JFrame {
    
    public conv1_0() {
        initComponents();
      setLocationRelativeTo(null);
      //setResizable(false);
      this.setTitle("convertidor de temperaturas");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de convercíon", "Celsius a Fahrenheit", "Celsius a kelvin", "Celsius a Rankine", "Celsius a Réaumu", "Fahrenheit  a Celsius", "Fahrenheit a Kelvin", "Fahrenheit a Rankine", "Fahrenheit a Réaumu", "Kelvin a Celsius", "Kelvin a Fahrenheit", "Kelvin a Rankine", "Kelvin a Rèaumu", "Rèaumu a Celsius", "Réaumu a Fahrenheit", "Rèaumu a Kelvin", "Rèaumu a Rankine" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aKeyTyped(evt);
            }
        });

        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String  n1;
        double result, k;
        n1 = a.getText();
        
        DecimalFormat decimales = new DecimalFormat("0.0000");
        
        JComboBox x = (JComboBox) evt.getSource();
        
        String q = "Celsius a Fahrenheit";
        String w = "Celsius a kelvin";
        String e = "Celsius a Rankine";
        String r = "Celsius a Réaumu";
        String t = "Fahrenheit  a Celsius";
        String y = "Fahrenheit a Kelvin";
        String u = "Fahrenheit a Rankine";
        String p = "Fahrenheit a Réaumu";
        String z = "Kelvin a Celsius";
        String s = "Kelvin a Fahrenheit";
        String d = "Kelvin a Rankine";
        String f = "Kelvin a Rèaumu";
        String g = "Rèaumu a Celsius";
        String h = "Réaumu a Fahrenheit";
        String j = "Rèaumu a Kelvin";
        String n = "Rèaumu a Rankine";
        String str = (String) x.getSelectedItem();
        
        if (a.getText().equals("")) {
            Object MSJ = "verifica la cantidad";
            JOptionPane.showMessageDialog(null, MSJ, "", JOptionPane.ERROR_MESSAGE);
        } else {
            if (x.getSelectedItem().equals(q)) {
                k = Double.parseDouble(n1);
                
                result = (k * 1.8) + 32;
                b.setText("" + decimales.format(result) + "" + "ºC");
            }
            if (x.getSelectedItem().equals(w)) {
                k = Double.parseDouble(n1);
                
                result = (k + 273.15);
                b.setText("" + decimales.format(result) + "" + "ºK");
            }
            if (x.getSelectedItem().equals(e)){
                 k = Double.parseDouble(n1);
                 
                 result=(k*1.8)+491.67;
                 b.setText(""+decimales.format(result)+""+"ºR");
                
            }
            if (x.getSelectedItem().equals(r)){
                k = Double.parseDouble(n1);
                
                result=(k*.8000);
                b.setText(""+decimales.format(result)+""+"Rè");
            }
            if (x.getSelectedItem().equals(t)){
                k = Double.parseDouble(n1);
                
                result=(k-32)/1.8;
                b.setText(""+decimales.format(result)+""+"ºc");
            }
            if(x.getSelectedItem().equals(y)){
                k = Double.parseDouble(n1);
                
                result=((5*(k-32))/9)+273.15;
                b.setText(""+decimales.format(result)+""+"ºk");
                
            }
            {
                if(x.getSelectedItem().equals(u)){
                    k = Double.parseDouble(n1);
                    
                    result=(k+459.67);
                    b.setText(""+decimales.format(result)+""+"Ra");
                }
            {
                if(x.getSelectedItem().equals(p)){
                    k=Double.parseDouble(n1);
                    
                    result=((4*(k-32)/9));
                    b.setText(""+decimales.format(result)+""+"Rè");
                }
            }
            {
                 if(x.getSelectedItem().equals(z)){
                    k=Double.parseDouble(n1);
                    
                    result=(k-273.15);
                    b.setText(""+decimales.format(result)+""+"ºc");
                 }    
//           {
//                 if(x.getSelectedItem().equals(s))
//                     k=Double.parseDouble(n1);
//                             
//                    result=((9*(k-273.15)/5))+32;
//                    b.setText(""+decimales.format(result)+""+"ºF");
//           }
            }
                if(x.getSelectedItem().equals(d)){
                    k=Double.parseDouble(n1);
                    
                    result=((9*(k-273.15)/5)+491.67);
                    b.setText(""+decimales.format(result)+""+"Ra");
                    
                }
            }
            {
                if(x.getSelectedItem().equals(f)){
                    k=Double.parseDouble(n1);
                    
                    result=(4*(k-273.15)/5);
                    b.setText(""+decimales.format(result)+""+"Rè");
                }
            }
        
            {
                if(x.getSelectedItem().equals(g)){
                    k=Double.parseDouble(n1);
                    
                    result=(k*.8000);
                    b.setText(""+decimales.format(result)+""+"ºc");
                }
            }
            {
                if(x.getSelectedItem().equals(h)){
                    k=Double.parseDouble(n1);
                    
                    result=((9*k)/4)+32;
                    b.setText(""+decimales.format(result)+""+"ºF");
                }
            }
            {
                if(x.getSelectedItem().equals(j)){
                    k=Double.parseDouble(n1);
                    
                    result=(k/.8000)+273.15;
                    b.setText(""+decimales.format(result)+""+"ºK");
                }
            }
            {
                if(x.getSelectedItem().equals(n)){
                    k=Double.parseDouble(n1);
                    
                    result=(9*k/4)+491.67;
                    b.setText(""+decimales.format(result)+491.67);
                }
            }

    }//GEN-LAST:event_jComboBox2ActionPerformed
    }    
    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            a.setText("");
        }
    }//GEN-LAST:event_aKeyTyped

    private void bKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            getToolkit().beep();
            evt.consume();
            b.setText("");
        }
    }//GEN-LAST:event_bKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conv1_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conv1_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conv1_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conv1_0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conv1_0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JComboBox<String> jComboBox2;
    // End of variables declaration//GEN-END:variables
}
